vim.g.mapleader = " "

require("config.options")
require("config.keymaps")
require("plugins.catppuccin")
require("plugins.mini-icons")
require("plugins.which-key")
require("plugins.cmp")
require("plugins.mason-lspconfig")
require("plugins.toggleterm")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.fzf-lua")
require("plugins.conform")
require("plugins.mini-files")
require("plugins.grug-far")
require("plugins.mini-statusline")
